{% set name = "perspective" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # - url: https://github.com/finos/perspective/actions/runs/10906536453/artifacts/1943747050
  #   sha256: 7d711fb449aee8b90a678e6877b1163b1cb86216d1c4e382dd982a4a49c986b7
  #   patches:
  #     - patches/fix_windows.diff

  # - url: https://github.com/finos/perspective/archive/refs/tags/v{{ version }}.tar.gz
  #   sha256: f3f8219da29a74542b42d92b79e988b471f6414bd74eb51a6c46f043876c18f4
  #   folder: perspective
  #   patches:
  #     - patches/shared_boost.diff
  #     - patches/fix_flags.diff
  #     - patches/fix_arrow.diff

  git_url: https://github.com/finos/perspective.git
  git_rev: python-imports
  # git_depth: 1

build:
  number: 1
  skip: True  # [py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.4,<2.0                     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cmake
    - make
    - libprotobuf
    - nodejs >=16 # XXX(tom): check version
  host:
    - python
    - pip
    - maturin >=1.4,<2.0
    - libboost-devel
  run:
    - python
    - jinja2 >=2.0,<4
    - ipywidgets >=7.5.1,<9
    - python-dateutil <3,>=2.8.0
    - traitlets <6,>=4.3.2

test:
  imports:
    - perspective

outputs:
  - name: perspective
  # - name: perspective-python
  #   requirements:
  #     build:
  #       - {{ stdlib("c") }}
  #     host:
  #       - python
  #     run:
  #       - python
  #       - perspective ={{ version }}

  # TODO this is supposed to work, but fails with weird
  # bugs. Try again in the future
  # - name: perspective_python
  #   build:
  #     noarch: python
  #   requirements:
  #     host:
  #       - python
  #     run:
  #       - python
  #       - {{ pin_subpackage("perspective", exact=True) }}

about:
  home: http://github.com/finos/perspective
  license: Apache-2.0
  license_family: Apache
  license_file:
    - perspective-cpp/LICENSE.md
  summary: Streaming pivot visualization via WebAssembly
  description: Streaming pivot visualization via WebAssembly
  dev_url: https://github.com/finos/perspective

extra:
  recipe-maintainers:
    - timkpaine
    - texodus
    - sc1f
