{% set name = "perspective" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # - url: https://github.com/finos/perspective/actions/runs/10906536453/artifacts/1943747050
  #   sha256: 7d711fb449aee8b90a678e6877b1163b1cb86216d1c4e382dd982a4a49c986b7
  #   patches:
  #     - patches/fix_windows.diff

  # - url: https://github.com/finos/perspective/archive/refs/tags/v{{ version }}.tar.gz
  #   sha256: f3f8219da29a74542b42d92b79e988b471f6414bd74eb51a6c46f043876c18f4
  #   folder: perspective
  #   patches:
  #     - patches/shared_boost.diff
  #     - patches/fix_flags.diff
  #     - patches/fix_arrow.diff

  git_url: https://github.com/finos/perspective.git
  git_rev: v3.1.0
  patches:
    - patches/fix_boost_install.diff
    - patches/disable_abi3.diff
    - patches/disable_explicit_manylinux.diff
  # git_depth: 1

build:
  number: 1
  skip: True  # [py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.4,<2.0                     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    # - {{ stdlib('cxx') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cmake
    - make
    - nodejs >=16 # XXX(tom): check version
    - pnpm
    - pkg-config
    - git
    - wget # to download boost sources from install_tools.mjs
    # XXX(tom): emsdk? no, use `jupyterlab` tooling to build extension
    - xsimd # XXX(tom): Andrew says we shouldn't need this b/c we disable SIMD in arrow build
    - lz4 # XXX(tom): likewise, this should be built from source downloaded by psp repo script
    - wheel
    - coreutils
  host:
    - python
    - pip
    - maturin >=1.4,<2.0
    # - libboost-devel
  run:
    - python

test:
  imports:
    - perspective

# outputs:
#   - name: perspective
#     type: wheel
#     files:
#       - rust/target/wheels/perspective_python-*.whl

  # - name: perspective-python
  #   requirements:
  #     build:
  #       - {{ stdlib("c") }}
  #     host:
  #       - python
  #     run:
  #       - python
  #       - perspective ={{ version }}

  # TODO this is supposed to work, but fails with weird
  # bugs. Try again in the future
  # - name: perspective_python
  #   build:
  #     noarch: python
  #   requirements:
  #     host:
  #       - python
  #     run:
  #       - python
  #       - {{ pin_subpackage("perspective", exact=True) }}

about:
  home: http://github.com/finos/perspective
  license: Apache-2.0
  license_family: Apache
  license_file:
    - perspective-cpp/LICENSE.md
  summary: Streaming pivot visualization via WebAssembly
  description: Streaming pivot visualization via WebAssembly
  dev_url: https://github.com/finos/perspective

extra:
  recipe-maintainers:
    - timkpaine
    - texodus
    - sc1f
