{% set name = "perspective" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/finos/perspective.git
  git_rev: v3.1.0
  patches:
    # XXX(tom): clean up unused patches
    - patches/shared_boost.diff # can be combined with boost_headers_only.
    # XXX(tom): want to understand better what fix_flags.diff fixes.
    # It resolved some include-path issues when switching to libboost-headers
    - patches/fix_flags.diff
    - patches/boost_headers_only.diff
    - patches/disable_abi3.diff
    - patches/delete_postinstall.diff
    - patches/delete_lint_package.diff
    - patches/fix_maturin.diff
    # - patches/fix_arch.diff # XXX(tom): not needed
    - patches/more_logging.diff
    - patches/disable_protobuf_src.diff
    - patches/fix_windows.diff

build:
  number: 0
  skip: True  # [py<39]
  ignore_run_exports_from:
  - libboost-devel

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.4,<2.0                     # [build_platform != target_platform]
    - libboost-headers                       # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cmake
    - make
    - nodejs
    - pnpm
    - pkg-config
    - libprotobuf # for protoc
    # XXX(tom): emsdk? no, use `jupyterlab` tooling to build extension from npm source (which will DL wasm blob)
    - xsimd # XXX(tom): Andrew says we shouldn't need this b/c we disable SIMD in arrow build
    - lz4 # XXX(tom): likewise, this should be built from source downloaded by psp repo script. and yet the build fails without it
    # Seems relevant, from the build spew:
    # By not providing "Findlz4.cmake" in CMAKE_MODULE_PATH this project has
    # asked CMake to find a package configuration file provided by "lz4", but
    # CMake did not find one.
  host:
    - python
    - pip
    - maturin >=1.4,<2.0
    - libboost-headers
  run:
    - python

test:
  imports:
    - perspective

about:
  home: http://github.com/finos/perspective
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE.md
  summary: Streaming pivot visualization via WebAssembly
  description: Streaming pivot visualization via WebAssembly
  dev_url: https://github.com/finos/perspective

extra:
  recipe-maintainers:
    - timkpaine
    - texodus
    - sc1f
