{% set name = "perspective" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/finos/perspective.git
  git_rev: v3.1.0
  patches:
    - patches/fix_boost_install.diff
    - patches/disable_abi3.diff
    - patches/disable_explicit_manylinux.diff
    - patches/delete_postinstall.diff
    - patches/delete_lint_package.diff
  # git_depth: 1

build:
  number: 0
  skip: True  # [py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.4,<2.0                     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cmake
    - make
    - nodejs
    - pnpm
    - pkg-config
    - git
    - wget # to download boost sources from install_tools.mjs
    - coreutils # sed, build.sh
    # XXX(tom): emsdk? no, use `jupyterlab` tooling to build extension from npm source (which will DL wasm blob)
    - xsimd # XXX(tom): Andrew says we shouldn't need this b/c we disable SIMD in arrow build
    - lz4 # XXX(tom): likewise, this should be built from source downloaded by psp repo script. and yet the build fails without it
    - nvim # XXX(tom): deleteme
  host:
    - python
    - pip
    - maturin >=1.4,<2.0
    - libstdcxx
  run:
    - python

test:
  imports:
    - perspective

about:
  home: http://github.com/finos/perspective
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE.md
  summary: Streaming pivot visualization via WebAssembly
  description: Streaming pivot visualization via WebAssembly
  dev_url: https://github.com/finos/perspective

extra:
  recipe-maintainers:
    - timkpaine
    - texodus
    - sc1f
