{% set name = "perspective-python" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/finos/perspective.git
  git_rev: v3.1.0
  patches:
    - patches/shared_boost.diff
    - patches/fix_flags.diff
    - patches/boost_headers_only.diff
    - patches/disable_abi3.diff
    - patches/delete_postinstall.diff
    - patches/delete_lint_package.diff
    - patches/fix_maturin.diff
    - patches/disable_protobuf_src.diff
    - patches/fix_windows.diff

build:
  number: 0
  skip: True  # [py<39 or py>=313]
  force_ignore_keys:
  # The nodejs dependency is used only to orchestrate the build.  The
  # perspective-python artifact has no runtime dependency on nodejs, so prevent
  # it from affecting the build hash.
  - nodejs

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.4,<2.0                     # [build_platform != target_platform]
    - libboost-headers                       # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    # git is required to build perspective, in order to clone its cmake
    # external projects. On windows, though, having git in the build
    # requirements causes conda-build to hang when cloning perspective's git
    # source, seems to be a conda-build bug.
    # Fortuantely the CI pipeline still passes on Windows without the dep.  For
    # local Windows builds, install git in the base system.
    - git  # [not win]
    - cmake
    - make
    - nodejs
    - pnpm
    - pkg-config
    - libprotobuf # for protoc
    # XXX(tom): emsdk? no, use `jupyterlab` tooling to build extension from npm source (which will DL wasm blob)
    # vendored Arrow build is broken here:
    #   CMake Warning at /home/conda/feedstock_root/build_artifacts/debug_1728070755516/work/rust/target/x86_64-unknown-linux-gnu/release/build/perspective-server-ee5a4104f4b826d0/out/build/arrow-src/cpp/cmake_modules/Findlz4Alt.cmake:29 (find_package):
    - xsimd # XXX(tom): Andrew says we shouldn't need this b/c we disable SIMD in arrow build
    - lz4 # XXX(tom): likewise, this should be built from source downloaded by psp repo script. and yet the build fails without it
    # Seems relevant, from the build spew:
    # By not providing "Findlz4.cmake" in CMAKE_MODULE_PATH this project has
    # asked CMake to find a package configuration file provided by "lz4", but
    # CMake did not find one.
  host:
    - python
    - pip
    - maturin >=1.4,<2.0
    - libboost-headers
  run:
    - python

test:
  imports:
    - perspective

about:
  home: http://github.com/finos/perspective
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE.md
  summary: Streaming pivot visualization via WebAssembly
  description: Streaming pivot visualization via WebAssembly
  dev_url: https://github.com/finos/perspective

extra:
  recipe-maintainers:
    - timkpaine
    - texodus
    - sc1f
